### ISSUE TITLE
User Feedback: Hidden Elements

### ISSUE THREAD

**Issue by MRH4287** [MRH4287/FFNetParser#45]
**This is a Suggestion that was made with the Chrome-Feedback System.**

*This Entry exists for referencing and discussion. If you are the user, who made the request, feel free to write a comment.*

------------

`
That's for situations when you click 'Show hidden elements' and they are shown but without any indication so you don't know immediately which stories were hidden
`

Posted: 22.12.2015

**Comment by MRH4287** [comment]
If you have an idea, how to make it better, please suggest it.
If i change too much of the style, every filter that might be applied additional isn't visible anymore.

**Comment by AndyScull** [comment]
Right now, black borders are sufficient.
But if you really want to make a perfect plugin or just bored, this is how it could be improved - 
IMO, a nice way to implement this would be to have a switch-like button or link, to show/hide hidden entries. Maybe an entry in site main menu (the one with 'Menu' and 'Filter' entries).
This switch in script should act like a flag, if it's enabled - script just skips setting visibility attribute and adds usual attributes like highlights, icons, etc (currently hidden items are ignored by highlighting part of code). I am okay if I have to reload a page to apply this switch change
This way, it would be possible to manage stories on a page - quickly see those that are bad/good/whatever, change them around or just see how colorful the page is with all those highlighted stories

**Comment by MRH4287** [comment]
Well .. currently i have a Link "Show Elements that are hidden by ...".
I could make that a toggle button / link ...

Because as it is, the Highlighter and Filter are two separate systems.
They use the same mechanics (even the same data-structure), but can be used independently from each other.
 If i add a button to the "Menu", where all Filters are defined, no one would know to look there.

I could add a Filter option to force the visibility though.
If this Flag is applied (either via Filter or Highlighter) the element is forced to stay visible, even when another filter (or option) would normally hide it.
Except maybe the "Read only" feature ;)

**Comment by AndyScull** [comment]
Well, it was just a small thought as this would be useful only in few situations.
The hidden checkbox can always be unchecked in category editor, pretty fast method unless there's 5 or more categories

**Comment by MRH4287** [comment]
I think about it ...
I leave this Issue open, maybe i get a good idea at some point :D

PS: I disabled the Chrome Web-Store Comments, because i don't get messages on them :/
So, for further requests, please post them here (as you already did ^^) 

Have a nice day ^^
