### ISSUE TITLE
Support for Scryer?

### ISSUE THREAD

**Issue by dlehman83** [MRH4287/FFNetParser#48]
Would it be possible to add support for Scryer?
https://scryer.darklordpotter.net/

It would be good to have the stories I've already highlighted show up on scryer as highlighted too.  

Thank you

**Comment by MRH4287** [comment]
Hi.
I've never heared of that system before.
But i know what they are using: Lucene.

What Support do you think of?
Can you tell me more about the system?

It looks interesting, but i don't have much time in the next weeks. But if the developers of Scryer want to, an integration into my script would be possible. Lucene (or Elastic Search) support Regular Expressions.

**Comment by MRH4287** [comment]
For reference:
https://gitlab.com/projectdlp/scryer/issues/1

**Comment by dlehman83** [comment]
Hello ,
I don't use the parser to search for stories, I just hide or highlight them.  I mark all the stories I have read, or stories I don't want to read so they do not show up in my search anymore.  I also highlight wip stories I am currently reading.  
Scryer has plans to mark stories as read
https://forums.darklordpotter.net/showthread.php?t=32979

However I've got a huge config file with you for all the stories I've hidden over the years.  
If that config file could apply to the scryer site matched by story id it would be very nice.

**Comment by MRH4287** [comment]
I've sent a request to the developers of Scryer.
In general, that shouldn't be a problem. Currently I am busy  with real life.
But I'll see what I can do if I have more time on my hands.

**Comment by MRH4287** [comment]
Just FYI: I am currently working on this task.
But it's quite a heavy restructure of my code.

I can't give you an ETA on this, because i don't know how much time i have and how long i'll need.
Have a nice day ;)

**Comment by MRH4287** [comment]
You might have noticed, but i am not very active on this project anymore.
I don't have the time to invest in new features that i ultimatly never use.

Closed, because it will never happen anyway.
