### ISSUE TITLE
Extension not working at all, parser pop-up not showing and unexpected redirecting to the developer's website

### ISSUE THREAD

**Issue by NinfaRoma41** [MRH4287/FFNetParser#50]
First, I am the noobest noob to ever enter this site and I am very, very sorry for bothering you with this, but, for some reason, FanFiction Parser is not working at all. Even the logo in Chrome's toolbar is greyed, like inactive extensions tend to be shown. When I click on it, I'm being redirected to your website and that's it. No Story Parser pop-up at all-

I already tried to uninstall and reinstall it, but still it not working and I have no clue for why this might be happening, and I might not be the only one having this problem.

I hope you can find this useful somehow and thank you for all your work. Please have a lovely week. 
Cheers.

**Comment by MRH4287** [comment]
Hey,
the extension only adds scripts to two sites:
https://www.fanfiction.net/
and
https://www.fictionpress.com/

The Logo on the Toolbar doesn't do anything.
You can ignore that, or remove it from the Toolbar.

Please check the Wiki for more information:
https://github.com/MRH4287/FFNetParser/wiki

Or ask me :)
